describe('Not Logged In', () => {
    it('Landing page successfully loads', () => {
        cy.visit('/')
        .viewport(320, 480)
        .screenshot('landing_page_mobile')
        .viewport(568, 320)
        .screenshot('landing_page_mobile_landscape')
        .viewport(768, 1024)
        .screenshot('landing_page_tablet')
        .viewport(992, 768)
        .screenshot('landing_page_desktop')
        .viewport(1200, 900)
        .screenshot('landing_page_large_desktop')
    })

    it('Register page successfully loads', () => {
        cy.visit('/register')
        .viewport(320, 480)
        .screenshot('register_page_mobile')
        .viewport(568, 320)
        .screenshot('register_page_mobile_landscape')
        .viewport(768, 1024)
        .screenshot('register_page_tablet')
        .viewport(992, 768)
        .screenshot('register_page_desktop')
        .viewport(1200, 900)
        .screenshot('register_page_large_desktop')
    })

    it('Login page successfully loads', () => {
        cy.visit('/login')
        .viewport(320, 480)
        .screenshot('login_page_mobile')
        .viewport(568, 320)
        .screenshot('login_page_mobile_landscape')
        .viewport(768, 1024)
        .screenshot('login_page_tablet')
        .viewport(992, 768)
        .screenshot('login_page_desktop')
        .viewport(1200, 900)
        .screenshot('login_page_large_desktop')
    })

    it('Contact page successfully loads', () => {
        cy.visit('/contact')
        .viewport(320, 480)
        .screenshot('contact_page_mobile')
        .viewport(568, 320)
        .screenshot('contact_page_mobile_landscape')
        .viewport(768, 1024)
        .screenshot('contact_page_tablet')
        .viewport(992, 768)
        .screenshot('contact_page_desktop')
        .viewport(1200, 900)
        .screenshot('contact_page_large_desktop')
    })
})